{
 "title": "Asset Performance",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Asset",
    "query": "Select distinct Asset From DeviceData"
   },
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "1400" }
  ]
 },
 "panels": [
  {
   "title": "OEE",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select a.[time],[Availability]*[Quality]*[Performance] as OEE \nfrom GetAvailability($__timeFrom(), $__timeTo(), '$Asset', 0) a \njoin GetQuality($__timeFrom(), $__timeTo(), '$Asset', 0) q on (a.[time]=q.[time])\njoin GetPerformance($__timeFrom(), $__timeTo(), '$Asset', $idealRunrate, 0) p on (a.[time]=p.[time])\n"
    }
   ]
  },
  {
   "title": "OEE Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select [time],[Running Status] from GetStatus($__timeFrom(), $__timeTo(), '$Asset') order by [time]"
    },
    {
     "rawSql": "select a.[time],[Availability]*[Quality]*[Performance] as OEE \nfrom GetAvailability($__timeFrom(), $__timeTo(), '$Asset', 1) a \njoin GetQuality($__timeFrom(), $__timeTo(), '$Asset', 1) q on (a.[time]=q.[time])\njoin GetPerformance($__timeFrom(), $__timeTo(), '$Asset', $idealRunrate, 1) p on (a.[time]=p.[time])\norder by [time]"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Availability] from GetAvailability($__timeFrom(), $__timeTo(), '$Asset', 0)"
    }
   ]
  },
  {
   "title": "Availability Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 5, "y": 5 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select [time],[Running Status] from GetStatus($__timeFrom(), $__timeTo(), '$Asset') order by [time]"
    },
    {
     "rawSql": "select [time],[Availability] from GetAvailability($__timeFrom(), $__timeTo(), '$Asset', 1) order by [time]"
    }
   ]
  },
  {
   "title": "Quality",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Quality] from GetQuality($__timeFrom(), $__timeTo(), '$Asset', 0)"
    }
   ]
  },
  {
   "title": "Quality Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 5, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select [time], ItemCount as [Good Item Count] from GetItemCounts($__timeFrom(), $__timeTo(), '$Asset', 1,1) order by [time]"
    },
    {
     "rawSql": "select [time], ItemCount as [Bad Item Count] from GetItemCounts($__timeFrom(), $__timeTo(), '$Asset', 0,1) order by [time]"
    },
    {
     "rawSql": "select [time], [Quality] from GetQuality($__timeFrom(), $__timeTo(), '$Asset', 1) order by [time]"
    },
    {
     "rawSql": "select [time],[Running Status] from GetStatus($__timeFrom(), $__timeTo(), '$Asset') order by [time]"
    },
    {
     "rawSql": "select convert(datetime2, $__timeFrom()) as [time], $idealRunrate as [Ideal Runrate]\nunion ALL\nselect convert(datetime2, $__timeTo()) as [time], $idealRunrate as [Ideal Runrate]"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Performance] from GetPerformance($__timeFrom(), $__timeTo(), '$Asset', $idealRunrate, 0)"
    }
   ]
  },
  {
   "title": "Performance Trend",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "select [time], ItemCount as [Good Item Count] from GetItemCounts($__timeFrom(), $__timeTo(), '$Asset', 1,1) order by [time]"
    },
    {
     "rawSql": "select [time], ItemCount as [Bad Item Count] from GetItemCounts($__timeFrom(), $__timeTo(), '$Asset', 0,1) order by [time]"
    },
    {
     "rawSql": "select [time], [Performance] from GetPerformance($__timeFrom(), $__timeTo(), '$Asset', $idealRunrate, 1) order by [time]\r\n"
    },
    {
     "rawSql": "select [time],[Running Status] from GetStatus($__timeFrom(), $__timeTo(), '$Asset') order by [time]"
    },
    {
     "rawSql": "select convert(datetime2, $__timeFrom()) as [time], $idealRunrate as [Ideal Runrate]\nunion ALL\nselect convert(datetime2, $__timeTo()) as [time], $idealRunrate as [Ideal Runrate]"
    }
   ]
  }
 ]
}