{
 "title": "Asset Benchmarking",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Asset",
    "query": "Select distinct Asset From DeviceData"
   },
   { "name": "idealRunrate", "label": "Ideal Run Rate (items/min)", "query": "1400" }
  ]
 },
 "panels": [
  { "title": "[[Asset]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Asset" },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Availability] from GetAvailability($__timeFrom(), $__timeTo(), $Asset, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 1 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Quality",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Quality] from GetQuality($__timeFrom(), $__timeTo(), $Asset, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 1 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Performance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Performance] from GetPerformance($__timeFrom(), $__timeTo(), $Asset,$idealRunrate, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 1 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "OEE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select a.[time],[Availability]*[Quality]*[Performance] as OEE \nfrom GetAvailability($__timeFrom(), $__timeTo(), $Asset, 0) a \njoin GetQuality($__timeFrom(), $__timeTo(), $Asset, 0) q on (a.[time]=q.[time])\njoin GetPerformance($__timeFrom(), $__timeTo(), $Asset, $idealRunrate, 0) p on (a.[time]=p.[time])\n"
    }
   ]
  },
  { "title": "[[Asset]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Availability",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Availability] from GetAvailability($__timeFrom(), $__timeTo(), $Asset, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 9 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Quality",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Quality] from GetQuality($__timeFrom(), $__timeTo(), $Asset, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 10, "y": 9 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>X</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "Performance",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select [time],[Performance] from GetPerformance($__timeFrom(), $__timeTo(), $Asset,$idealRunrate, 0)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 16, "y": 9 },
   "options": {
    "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
   },
   "content": "<div align=center>\r\n\r\n<table class=MsoTableGrid border=1 cellspacing=0 cellpadding=0\r\n style='border:none;'>\r\n <tr style=''>\r\n  <td width=623 style='height:190.0pt'>\r\n  <p align=center style='text-align:center'><b><span style='font-size:60.0pt;color:grey'>=</span></b></p>\r\n  </td>\r\n </tr>\r\n</table>\r\n\r\n</div>"
  },
  {
   "title": "OEE",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select a.[time],[Availability]*[Quality]*[Performance] as OEE \nfrom GetAvailability($__timeFrom(), $__timeTo(), $Asset, 0) a \njoin GetQuality($__timeFrom(), $__timeTo(), $Asset, 0) q on (a.[time]=q.[time])\njoin GetPerformance($__timeFrom(), $__timeTo(), $Asset, $idealRunrate, 0) p on (a.[time]=p.[time])\n"
    }
   ]
  }
 ]
}